### PR TITLE
Add Groups.replies and Channels.replies to the web api

### PR DESCRIPTION
**Pull request by AnilRedshift**
I needed these API's, so I copy/pasted them from the docs.

I saw the discussion about these being up-to-date, but in the meantime, here's a bandaid that worked for me.

Thanks,
Anil

### CODE REVIEW

**Comment by AnilRedshift** [comment]
🏏

**Comment by BlakeWilliams** [comment]
Sorry, just got around to this. I think this is likely the way this will have to maintained at least in the short term.

Can you open a separate PR for the user changes though?

**Comment by AnilRedshift** [comment]
@BlakeWilliams: Sorry, I didn't realize I made a PR against my master branch. I'll fix this one up shortly.

**Comment by adamu** [comment]
I was just about to make a PR to add `chat.postEphemeral`, but see you've added it here. Looking forward to the merge. 👍

**Comment by AnilRedshift** [comment]
@BlakeWilliams this is now up to date

**Comment by BlakeWilliams** [comment]
thanks!

**Pull request merged**
