### PR TITLE
Send message with threaded replies to messages in channels

### PR DESCRIPTION
**Pull request by rkstarnerd**
This PR gives the ability to reply to messages in channels as a threaded response.

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
@rkstarnerd This is awesome, can you resolve the conflicts and ping me? Would love to get this merged.

**Comment by rkstarnerd** [comment]
> @rkstarnerd This is awesome, can you resolve the conflicts and ping me? Would love to get this merged.

Hi Blake, I've resolved the conflicts. Let me know if there's anything else needed. Thank you!

**Comment by acconrad** [comment]
@BlakeWilliams if you're okay with it I can merge this in

**Comment by BlakeWilliams** [comment]
Sounds good, I've had this one on my TODO list but I haven't gotten around to it. 👍

**Pull request merged**
