### PR TITLE
Use hex websocket_client package.

### LINKED ISSUE #56: Use hex hosted websocket_client
It seems like the erlang websocket_client library was forked to https://github.com/sanmiguel/websocket_client. Since this is hosted on hex and is being actively developed elixir-slack should use this library instead.

### PR DESCRIPTION
**Pull request by christhekeele**
Closes #56.

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
I ran into issues when running this with an actual bot when I initially spiked it out. Have you tested this out with a real bot?

I can share the code of a test bot if you need.

**Comment by christhekeele** [comment]
Did you mean for this comment to go to #61? Haven't tried with a real bot, just manual overrequesting from `iex`.

**Comment by christhekeele** [comment]
Oh I see, you're right this is completely wrong.

**Comment by BlakeWilliams** [comment]
Right, I think it's going to be a slightly painful change.

**Comment by BlakeWilliams** [comment]
Closing since this seems stale.

**Pull request closed without merging**
