### PR TITLE
Minor: fixed unused variable warning

### PR DESCRIPTION
**Pull request by pavellishin**

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
Nice find, thank you!

**Comment by pavellishin** [comment]
Thanks; I was looking at tackling #169, and figured I'd run the tests first.

**Comment by pavellishin** [comment]
(To be totally honest, I want that sweet, sweet Hacktoberfest cred, but I _also_ came up with a Slack-based game idea in the shower this morning, so I might be using this for that...)

**Comment by BlakeWilliams** [comment]
Hacktoberfest is pretty rad. Thank you for the contributions regardless. :)

**Pull request merged**
