### PR TITLE
update httpoison

### PR DESCRIPTION
**Pull request by KazuCocoa**
To use `httpoison` 0.8.x, could you update its dependency ?
And could you release new version ?

### CODE REVIEW

**Comment by KazuCocoa** [comment]
I checked only `mix test` and test with my some library.

**Comment by BlakeWilliams** [comment]
LGTM! Thanks!

**Comment by KazuCocoa** [comment]
Thanks for quick merge !

**Comment by BlakeWilliams** [comment]
No problem! I also released `0.4.0` which should have this change included.

**Pull request merged**
