### PR TITLE
Allow websocket pid naming

### PR DESCRIPTION
**Pull request by qgadrian**
Modified `Slack.start_link/2` to `Slack.start_link\3` to allow register the websocket pid with the desired name.

Name is optional, `Slack.start_link` will be able to be called with just one args (token).

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
Unfortunately this change conflicts with #86 so I think this may have to be modified once that gets in.

I think the best bet for that is to make the 4th argument an options keyword list or map that accepts `module_name` as a parameter as well as `client`. I may have a PR or merge something similar in that you could hook into in a bit.

If you aren't interested in changing the code to fit the new format let me know and I'll take a stab at it. :)

**Comment by qgadrian** [comment]
Hi @BlakeWilliams!

I did a rebase over the last commit, but I couldn't make the library work already, seems that it's not connecting to the slack API and the Supervisor terminates the Slack.Rtm process. 

I bet this is not because of this PR, but I'll look into it today and open an issue if I can't figure out what's going on.

**Comment by qgadrian** [comment]
@qgadrian:
> (...) but I couldn't make the library work already, seems that it's not connecting to the slack API and the Supervisor terminates the Slack.Rtm process

Ok, I had a websocket library dependency on my project so I wasn't using the one configured in your library.

@BlakeWilliams:
> I think the best bet for that is to make the 4th argument an options keyword list or map that accepts module_name as a parameter as well as client.

I didn't include anything about `module_name`, as I don't really know if that would be helpful (maybe you tried to mean `pid_name` instead?). 

Anyway, I just added a `name:` as an option to the `Slack.start_link/4` function, so this PR can me merged whenever you want.

See you ;)

**Comment by BlakeWilliams** [comment]
Merged as a2e8de4162e69e107f1cf9ae12948ae40eea9787

**Comment by BlakeWilliams** [comment]
Thanks for the contribution!

**Pull request closed without merging**
