### PR TITLE
Adding new method ProfileSet to Slack.Web.Users.

### PR DESCRIPTION
**Pull request by tubedude**
This PR creates the ProfileSet for Slack.Web.Users as specified at: https://api.slack.com/methods/users.profile.set

It also bumps up some dependencies.

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
Did you use the mix task to update the JSON files? Also, can we make a separate PR for swapping out JSX and Poison?

**Comment by davydog187** [comment]
I had previously swapped out JSX with Poision. This PR needs to be rebased

**Comment by tubedude** [comment]
Yep.. i f**ked up the GIt and brought the last commit along with this one. I'll restart fresh and repost this PR.

**Comment by acconrad** [comment]
Actually I'm going to close this PR because this method already exists in the `lib/slack/web/docs` folder

**Pull request closed without merging**
