### PR TITLE
Add example application.

### PR DESCRIPTION
**Pull request by afaur**
This PR is a work in progress to add an slack example bot to the elixir-slack repository.
After I figure out how to get it working I would like to..

- Have a readme file that explains how to add small bits of functionality to the bot.
- Keep this example up to date with the latest elixir-slack version.

Right now when running the project I get the following error:

```
== Compilation error on file lib/slack_example_box.ex ==
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.105.0>, #Reference<0.0.1.122>, {:client, :undefined, :hackney_dummy_metrics, :hackney_ssl_transport, 'slack.com', 443, "slack.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
    src/hackney_client/hackney_manager.erl:66: :hackney_manager.init_request/1
    src/hackney_client/hackney_manager.erl:56: :hackney_manager.new_request/1
    src/hackney_connect/hackney_connect.erl:183: :hackney_connect.socket_from_pool/4
    src/hackney_connect/hackney_connect.erl:36: :hackney_connect.connect/5
    src/hackney_client/hackney.erl:321: :hackney.request/5
    lib/httpoison/base.ex:375: HTTPoison.Base.request/9
    lib/slack/rtm.ex:6: Slack.Rtm.start/1
```

I'm sure this is just a result of my lack of understanding of how all this works.  Please advise on how to get this example to run properly.  This PR should resolve issue (https://github.com/BlakeWilliams/Elixir-Slack/issues/18).

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
That error looks like the slack token is incorrect, but I'd have to run it myself to be 100% sure.

I agree that there needs to be a new example application but I don't think this repo is the correct place for it. I think it should be in a separate repository and references from the readme.

**Comment by afaur** [comment]
@BlakeWilliams Sounds like a plan, would you like to create it or should I?  The token should be correct.  I think it's me misunderstanding how the start_link stuff works possibly?

**Comment by afaur** [comment]
@BlakeWilliams Maybe to keep the example up to date we could add it as a `git submodule` to this repo, that way we don't bloat this repo with the example.  This would alow for travis ci (once it's set up on this repo) to do the command `git submodule init --update` and have checks in place to allow it to indicate in the continuous integration build that the new functionality would break the example app.

**Comment by BlakeWilliams** [comment]
I don't think a `git submodule` fits here either. The example app itself should be separate.

If the goal here is more test coverage it would make more sense to me to write an integration test with a Slack server fake.

**Comment by afaur** [comment]
@BlakeWilliams That makes sense.  I think as long as we add travis to the example application (wherever it ends up living) it will make it easier for people to know if its working or not.

**Comment by afaur** [comment]
@BlakeWilliams Was able to get the example application to work finally.  I ended up needing a start method with an arity of 2 (`_state`, `_opts`) inside my module and had to run the start_link from inside there for some reason.

**Comment by afaur** [comment]
Closing this since the example will live in a different repo.

**Pull request closed without merging**
