### PR TITLE
Bump HTTPoison version

### PR DESCRIPTION
**Pull request by roehst**
Ok, now it shows the single bump commit

### CODE REVIEW

**Comment by roehst** [comment]
It probably will once mix deps.get is run, should it go with the commit?

**Comment by BlakeWilliams** [comment]
Yes please.

**Comment by roehst** [comment]
there you go

**Comment by mmartinson** [comment]
Is there a reason for 1.0 and not [1.1](https://github.com/edgurgel/httpoison/releases)?

**Pull request closed without merging**
